// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2YORNX-5Tr-n3zmOhGXw_1pq_AJfJQIQ',
    appId: '1:899317925609:web:f9cd17b39c9f1b8a119278',
    messagingSenderId: '899317925609',
    projectId: 'campuscrt',
    authDomain: 'campuscrt.firebaseapp.com',
    storageBucket: 'campuscrt.appspot.com',
    measurementId: 'G-Q7NN31HE73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3UD6MkHWsE0oJpVwsWyKK_AGRL-c7VE',
    appId: '1:899317925609:android:346035a8c592fd24119278',
    messagingSenderId: '899317925609',
    projectId: 'campuscrt',
    storageBucket: 'campuscrt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc7g8J0TdytNL6SZDJ1Uj_0cY2YAIoask',
    appId: '1:899317925609:ios:88a2004d62545fb9119278',
    messagingSenderId: '899317925609',
    projectId: 'campuscrt',
    storageBucket: 'campuscrt.appspot.com',
    iosBundleId: 'com.example.campusCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc7g8J0TdytNL6SZDJ1Uj_0cY2YAIoask',
    appId: '1:899317925609:ios:88a2004d62545fb9119278',
    messagingSenderId: '899317925609',
    projectId: 'campuscrt',
    storageBucket: 'campuscrt.appspot.com',
    iosBundleId: 'com.example.campusCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2YORNX-5Tr-n3zmOhGXw_1pq_AJfJQIQ',
    appId: '1:899317925609:web:3261e39e44e98ece119278',
    messagingSenderId: '899317925609',
    projectId: 'campuscrt',
    authDomain: 'campuscrt.firebaseapp.com',
    storageBucket: 'campuscrt.appspot.com',
    measurementId: 'G-SFF9TJZJ8V',
  );

}